name: CI/CD AWS

on:
  push:
    branches: [AWS-Infrastructure]

permissions:
  contents: write

jobs:
  pipeline:
    uses: ./.github/workflows/_pipeline.yml
    with:
      runner: self-hosted
      registry: ecr
    secrets: inherit